version: "3.9"
services:
  php:
    build: ./docker/php
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - mysql_data:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    ports:
      - "8080:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
